from pydantic import BaseModel, Field
from typing import Dict, Any, Optional, List, Union

# ---------------------------------------------------------
# 1. Granular Models (Maps to single items from frontend Parser)
# ---------------------------------------------------------

class DealDetail(BaseModel):
    """
    Maps to frontend deal object: { text: "...", count: 1, ... }
    """
    text: Optional[str] = None
    hasMore: Optional[bool] = False
    count: Optional[int] = 0
    all: Optional[List[str]] = []


class DealItem(BaseModel):
    """
    Maps to the normalized Deal object generated by frontend Parsers
    """
    id: str
    name: str
    platform: str
    
    # Optional fields (not all stores have these)
    url: Optional[str] = None
    rating: Optional[str] = None
    fee: Optional[str] = None
    time: Optional[str] = None
    pickupTime: Optional[str] = None
    isOpen: Optional[bool] = True
    image: Optional[str] = None
    cuisine: Optional[str] = None
    
    # Latitude/Longitude fields (Pydantic will attempt to cast string to float)
    lat: Optional[float] = Field(default=None, description="Store Latitude")
    lon: Optional[float] = Field(default=None, description="Store Longitude")

    # Nested Deal information
    deal: Optional[Union[DealDetail, Dict[str, Any]]] = None

    class Config:
        from_attributes = True


class ParsedDealsData(BaseModel):
    """
    Maps to 'parsed_deals' structure in payload
    { count: 10, items: [...] }
    """
    count: int
    items: List[DealItem]


# ---------------------------------------------------------
# 2. Core Payload (API Entry Model)
# ---------------------------------------------------------

class DealPayload(BaseModel):
    """
    Receives data packet from Chrome Extension (POST /ingest)
    Corresponds to Ingestion Layer in Architecture v1.0.0
    """
    platform: str = Field(..., description="ubereats, grubhub, or doordash")
    
    # Maps to raw.deals_raw table -> raw_json column (Always empty for privacy)
    raw_json: Dict[str, Any] = Field(..., description="Platform's native raw JSON response")
    
    # Maps to raw.deals_raw table -> parsed_deals column
    # Strict validation using ParsedDealsData model
    # If frontend structure doesn't match, API returns 422 error
    parsed_deals: ParsedDealsData = Field(..., description="Extension's normalized data with Lat/Lon")
    
    # Metadata (URL, Timestamp, version, etc.)
    metadata: Optional[Dict[str, Any]] = Field(default=None)

    class Config:
        from_attributes = True